angelasoler/WebServ

Makefile, main.cpp
Pra testar, utilize em outro terminal : '~$ telnet localhost 8080'
=> att-server

includes/Config.hpp, src/Config.cpp, src/main.cpp, test/webservtest.cpp
=> config-into-singleton-and-fix-tests-and-add-macros

.gitignore, includes/Connection.hpp, includes/EventLoop.hpp, src/Connection.cpp, src/EventLoop.cpp, src/Request.cpp, src/Response.cpp, src/main.cpp
=> abstrae funções de comunicação para classe connections

includes/Config.hpp, src/Config.cpp, src/main.cpp, test/webservtest.cpp
=> 28 put argv to config

includes/Connection.hpp, includes/EventLoop.hpp, src/Connection.cpp, src/EventLoop.cpp, src/main.cpp
Excapsula inicialização de servers em classe connection
=> 31 restruct project

includes/Request.hpp, includes/Response.hpp, src/Request.cpp
=> feat - retorna metodo, routa e versão de http

includes/Config.hpp, includes/ParsePathInfo.hpp, includes/Request.hpp, includes/Response.hpp, serverRoot/index.html, src/Config.cpp, src/ParsePathInfo.cpp, src/Request.cpp, src/Response.cpp, src/printConfig.cpp, test/webservtest.cpp
=> 48 isolate response

config.conf, includes/ParsePathInfo.hpp, includes/Request.hpp, includes/Response.hpp, src/ParsePathInfo.cpp, src/Response.cpp
=> 50 parse fullpath correctly

includes/Request.hpp, includes/Response.hpp, src/ParsePathInfo.cpp, src/Response.cpp
=> 53 specify request and response parsing

includes/Delete.hpp, includes/Get.hpp, includes/Post.hpp, includes/Response.hpp, src/Delete.cpp, src/Get.cpp, src/Post.cpp, src/Response.cpp
=> 55 refactorate response

includes/Request.hpp, src/Connection.cpp, src/Request.cpp, src/Response.cpp
se recv retorna codigo de erro apenas ignora
=> fix - soluciona bug de fechamento por erro de recv

.gitignore, includes/Config.hpp, includes/Request.hpp, includes/Response.hpp, includes/TimeNow.hpp, src/Config.cpp, src/Request.cpp, src/Response.cpp, src/TimeNow.cpp, src/main.cpp, src/printConfig.cpp, test/subject-tests.cpp, test/webservtest.cpp
=> feat - send logs to respective files

includes/Connection.hpp, includes/Request.hpp, src/Connection.cpp, src/Request.cpp, src/Response.cpp
feat - trata retornos recv e send
Close #68
=> fix - fecha cliente e limpa fd do vetor

includes/Request.hpp, src/Get.cpp, src/ParsePathInfo.cpp, test/GET-curl-status-codes-tests.cpp.cpp
feat - trata get 403 e 404 com arquivo
=> GetRequest403

includes/ParseBodyInfo.hpp, includes/ParsePathInfo.hpp, includes/Request.hpp, src/ParseBodyInfo.cpp, src/ParsePathInfo.cpp, src/Request.cpp, test/config-tests.cpp, test/request-info-tests.cpp, test/upload.html
=> 58 parse body from request

includes/Config.hpp, src/Config.cpp, test/conf_test_files/InvalidServerId1.conf, test/conf_test_files/InvalidServerId1ValidServerId2.conf, test/conf_test_files/ThreeRoutes.conf, test/conf_test_files/TwoRoutes.conf, test/conf_test_files/TwoServersTwoRoutes.conf, test/config-tests.cpp
=> 84 fix config

src/RequestReader.cpp, test/POSTChunked-curl-tests.cpp, test/request-info-tests.cpp
=> 74 chunked request

includes/Config.hpp, src/Config.cpp
=> add-reservedPorts

includes/Delete.hpp, serverRoot/delete.html, src/Delete.cpp, test/DELETE-tests.cpp
=> 43 add delete

Makefile, includes/PrintRequestInfo.hpp, includes/Request.hpp, includes/RequestReader.hpp, src/ParseBodyInfo.cpp, src/PrintRequestInfo.cpp, src/Request.cpp, src/RequestReader.cpp
=> 105 save raw body

config.conf, includes/Config.hpp, includes/Post.hpp, serverRoot/uploads/serverUpload.html, src/Post.cpp, src/PrintRequestInfo.cpp, test/POST-Upload-curl-tests.cpp, test/request-info-tests.cpp, test/upload-tests/upload-config.conf
=> 114 fix post config

includes/Config.hpp, src/CGIServer.cpp, src/Config.cpp, src/Connection.cpp, src/main.cpp
The leaks were solved with a simple ``delete`` call int the **Config** class.
The fds part were the strange part to solve. Two loops were added to separately close the clients and servers fds. Now it's all working.
=> 121 limpar valgrind

Makefile, config.conf, includes/Request.hpp, includes/RequestReader.hpp, serverRoot/uploads/requirements.txt, src/Connection.cpp, src/Request.cpp, src/RequestReader.cpp, test/request-info-tests.cpp
=> 135 fix await read

includes/Connection.hpp, src/Get.cpp, src/RequestReader.cpp, src/Response.cpp, src/Server.cpp
=> 136 stress tests
